# Generated by Django 5.0.3 on 2024-03-26 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimg',
            name='link',
        ),
        migrations.RemoveField(
            model_name='productimg',
            name='video',
        ),
        migrations.AddField(
            model_name='productimg',
            name='img',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video')),
                ('link', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
