# Generated by Django 5.0.3 on 2024-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_productimg_link_remove_productimg_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner_img',
            field=models.ImageField(upload_to='banner-img/'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
