# Generated by Django 5.0.3 on 2024-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_avatar_cart_cartproduct_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='thumb-1.jpg', upload_to='avatar/'),
        ),
    ]
