# Generated by Django 5.0.3 on 2024-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
