# Generated by Django 5.0.3 on 2024-04-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_enterproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterproduct',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
