# Generated by Django 5.0.3 on 2024-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_date_enterproduct_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'No Faol'), (2, 'Yo`lda'), (3, 'Qaytarilgan'), (4, 'Qabul qilingan')], null=True),
        ),
    ]
