# Generated by Django 5.0.3 on 2024-04-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_cart_is_active_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
